package com.hackday.dao;

import com.hackday.po.NodeTable;

public interface NodeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodetable
     *
     * @mbggenerated
     */
    int insert(NodeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodetable
     *
     * @mbggenerated
     */
    int insertSelective(NodeTable record);
}