package com.hackday.dao;

import com.hackday.po.Page;

public interface PageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insertSelective(Page record);
}