package com.hackday.dao;

import com.hackday.po.Connection;

public interface ConnectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connection
     *
     * @mbggenerated
     */
    int insert(Connection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table connection
     *
     * @mbggenerated
     */
    int insertSelective(Connection record);
}