package com.hackday.dao;

import com.hackday.po.Constraint;

public interface ConstraintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constraint
     *
     * @mbggenerated
     */
    int insert(Constraint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constraint
     *
     * @mbggenerated
     */
    int insertSelective(Constraint record);
}